#!/usr/bin/env python3
"""
PredSea WW3 Wind Forcing Adapter from WRF d02 outputs.

Extracts 10m wind fields (U10, V10) from WRF NetCDF outputs (e.g. wrfout_d02_*),
interpolates them onto regular 1D lat-lon grids covering each of the 5 regional
domains, and generates CF-compliant wind.nc plus the ww3_prnc.nml,
ww3_shel.nml, and ww3_ounf.nml files required by WW3.

Supported regions:
  - alboran_1km
  - algerian_1km
  - balearic_1km
  - gulf_of_lion_1km
  - tyrrhenian_1km
"""
from __future__ import annotations

import argparse
import json
import sys
import traceback
from pathlib import Path
import numpy as np
import scipy.spatial
import xarray as xr

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT_BASE = PROJECT_ROOT / "simulation" / "marine" / "ww3" / "grids"

SEARCH_REGIONS_DIRS = [
    PROJECT_ROOT / "simulation" / "marine" / "regions",
    Path("/app/simulation/marine/regions"),
    Path("/workspace/repo/simulation/marine/regions"),
]

ALL_REGIONS = [
    "alboran_1km",
    "algerian_1km",
    "balearic_1km",
    "gulf_of_lion_1km",
    "tyrrhenian_1km",
]


def load_region(region_id: str) -> dict:
    for regions_dir in SEARCH_REGIONS_DIRS:
        profile_path = regions_dir / f"{region_id}.json"
        if profile_path.exists():
            return json.loads(profile_path.read_text())
    raise FileNotFoundError(
        f"No region profile for '{region_id}' found in any search path: {SEARCH_REGIONS_DIRS}"
    )


def _nml_time(value: np.datetime64) -> str:
    """WW3 namelist time format: 'YYYYMMDD HHMMSS'."""
    timestamp = value.astype("datetime64[s]").astype(object)
    return timestamp.strftime("%Y%m%d %H%M%S")


def _parse_wrf_time(ds: xr.Dataset) -> np.datetime64:
    """Robustly parse timestamp from WRF NetCDF 'Times' or 'XTIME' variable."""
    if "Times" in ds:
        t_val = ds["Times"].values
        if hasattr(t_val, "tobytes"):
            time_str = t_val.tobytes().decode("utf-8").strip()
        elif isinstance(t_val, np.ndarray):
            time_str = "".join(
                [c.decode("utf-8") if isinstance(c, bytes) else str(c) for c in t_val.ravel() if c]
            ).strip()
        else:
            time_str = str(t_val).strip()
        time_str = time_str.replace("_", "T")
        return np.datetime64(time_str[:19])
    elif "XTIME" in ds:
        return np.datetime64(ds["XTIME"].values[0], "m")
    else:
        raise ValueError("No time variable found in dataset")


def write_wind_netcdf(
    u_grid: np.ndarray,
    v_grid: np.ndarray,
    times: list[np.datetime64],
    lats: np.ndarray,
    lons: np.ndarray,
    output_path: Path,
) -> None:
    """Write a CF-compliant wind NetCDF matching ww3_prnc's FILE_NML contract."""
    dataset = xr.Dataset(
        {
            "U": (("time", "latitude", "longitude"), u_grid.astype(np.float32)),
            "V": (("time", "latitude", "longitude"), v_grid.astype(np.float32)),
        },
        coords={
            "time": np.array(times, dtype="datetime64[ns]"),
            "latitude": lats.astype(np.float32),
            "longitude": lons.astype(np.float32),
        },
    )
    dataset["time"].encoding["units"] = "seconds since 1970-01-01T00:00:00Z"
    dataset["time"].encoding["calendar"] = "standard"
    dataset.to_netcdf(output_path, format="NETCDF4_CLASSIC")


def render_ww3_prnc_nml(start: np.datetime64, end: np.datetime64, wind_filename: str) -> str:
    return f"""\
! Generated by scripts/prepare_ww3_wind_from_wrf.py.
&FORCING_NML
  FORCING%TIMESTART         = '{_nml_time(start)}'
  FORCING%TIMESTOP          = '{_nml_time(end)}'
  FORCING%FIELD%WINDS       = t
  FORCING%GRID%LATLON       = t
/

&FILE_NML
  FILE%FILENAME      = '{wind_filename}'
  FILE%LONGITUDE     = 'longitude'
  FILE%LATITUDE      = 'latitude'
  FILE%VAR(1)        = 'U'
  FILE%VAR(2)        = 'V'
/
"""


def render_ww3_shel_nml(region_id: str, start: np.datetime64, end: np.datetime64) -> str:
    start_text = _nml_time(start)
    end_text = _nml_time(end)
    return f"""\
! Generated by scripts/prepare_ww3_wind_from_wrf.py for region '{region_id}'.
&DOMAIN_NML
  DOMAIN%START  = '{start_text}'
  DOMAIN%STOP   = '{end_text}'
/

&INPUT_NML
  INPUT%FORCING%WINDS = 'T'
/

&OUTPUT_TYPE_NML
  TYPE%FIELD%LIST     = 'HS DIR SPR WND DTD FC CFX'
/

&OUTPUT_DATE_NML
  DATE%FIELD%START         = '{start_text}'
  DATE%FIELD%STRIDE        = '3600'
  DATE%FIELD%STOP          = '{end_text}'
/

&OUTPUT_PATH_NML
  PATH%GRD_OUT = './'
  PATH%PNT_OUT = './'
  PATH%RST_OUT = './'
/
"""


def render_ww3_ounf_nml(start: np.datetime64, end: np.datetime64) -> str:
    """Configure ww3_ounf to read ww3_shel's native ``out_grd.ww3`` output."""
    time_count = int((end - start) / np.timedelta64(1, "h")) + 1
    return f"""\
! Generated by scripts/prepare_ww3_wind_from_wrf.py.
! Schema verified against NOAA-EMC/WW3 develop branch model/nml/ww3_ounf.nml.
! ww3_ounf reads the fixed native input name 'out_grd.ww3', produced in
! PATH%GRD_OUT by ww3_shel; PATH%GRD_OUT = './' therefore places it here.

&FIELD_NML
  FIELD%TIMESTART  = '{_nml_time(start)}'
  FIELD%TIMESTRIDE = '3600'
  FIELD%TIMECOUNT  = '{time_count}'
  FIELD%LIST       = 'HS DIR SPR WND DTD FC CFX'
  FIELD%SAMEFILE   = T
  FIELD%TYPE       = 4
/

&FILE_NML
  FILE%PREFIX = 'ww3.'
  FILE%NETCDF = 4
/
"""


def extract_and_interpolate_wrf_wind(
    wrf_files: list[Path],
    region_id: str,
    output_dir: Path,
    res_deg: float = 0.025,
) -> dict:
    region = load_region(region_id)
    bbox = region["bbox"]
    
    # 1D target regular grid
    lons_1d = np.arange(
        bbox["longitude_min"] - 0.1,
        bbox["longitude_max"] + 0.1 + res_deg / 2.0,
        res_deg,
    )
    lats_1d = np.arange(
        bbox["latitude_min"] - 0.1,
        bbox["latitude_max"] + 0.1 + res_deg / 2.0,
        res_deg,
    )
    grid_lon2d, grid_lat2d = np.meshgrid(lons_1d, lats_1d)
    target_pts = np.column_stack([grid_lon2d.ravel(), grid_lat2d.ravel()])

    # Open first file to build KDTree interpolation mapping from WRF d02 2D mesh
    with xr.open_dataset(wrf_files[0]) as ds0:
        xlat = ds0["XLAT"].values[0] if "Time" in ds0["XLAT"].dims else ds0["XLAT"].values
        xlong = ds0["XLONG"].values[0] if "Time" in ds0["XLONG"].dims else ds0["XLONG"].values

    wrf_pts = np.column_stack([xlong.ravel(), xlat.ravel()])
    tree = scipy.spatial.cKDTree(wrf_pts)
    
    # Query 4 nearest neighbors for inverse distance weighting (IDW)
    dists, indices = tree.query(target_pts, k=4)
    # Prevent division by zero
    dists = np.maximum(dists, 1e-10)
    weights = 1.0 / dists
    weights /= weights.sum(axis=1, keepdims=True)

    times = []
    u_list = []
    v_list = []

    # Sort files by name to ensure chronological order
    sorted_files = sorted(wrf_files)
    for f in sorted_files:
        with xr.open_dataset(f) as ds:
            u10 = ds["U10"].values  # shape (Time, S_N, W_E) or (S_N, W_E)
            v10 = ds["V10"].values
            
            time_val = _parse_wrf_time(ds)
            times.append(time_val)

            # Reshape u10/v10 for spatial interpolation
            u_2d = u10[0] if u10.ndim == 3 else u10
            v_2d = v10[0] if v10.ndim == 3 else v10

            u_flat = u_2d.ravel()
            v_flat = v_2d.ravel()

            # IDW interpolation onto target grid
            u_interp = (u_flat[indices] * weights).sum(axis=1).reshape(grid_lat2d.shape)
            v_interp = (v_flat[indices] * weights).sum(axis=1).reshape(grid_lat2d.shape)

            u_list.append(u_interp)
            v_list.append(v_interp)

    u_stack = np.array(u_list)  # shape (Time, Lat, Lon)
    v_stack = np.array(v_list)

    start_time = times[0]
    end_time = times[-1]

    output_dir.mkdir(parents=True, exist_ok=True)
    wind_filename = "wind.nc"
    write_wind_netcdf(u_stack, v_stack, times, lats_1d, lons_1d, output_dir / wind_filename)

    (output_dir / "ww3_prnc.nml").write_text(
        render_ww3_prnc_nml(start_time, end_time, wind_filename)
    )
    (output_dir / "ww3_shel.nml").write_text(
        render_ww3_shel_nml(region_id, start_time, end_time)
    )
    (output_dir / "ww3_ounf.nml").write_text(
        render_ww3_ounf_nml(start_time, end_time)
    )

    manifest = {
        "schema_version": "predsea.ww3_forcing_input.v1",
        "region_id": region_id,
        "start_time": str(start_time),
        "end_time": str(end_time),
        "timestamps": len(times),
        "source": "WRF_d02",
        "grid_resolution_deg": res_deg,
        "grid_shape": list(u_stack.shape),
    }
    (output_dir / "forcing_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--wrf-dir",
        type=Path,
        required=True,
        help="Directory containing wrfout_d02_* NetCDF files",
    )
    parser.add_argument(
        "--regions",
        nargs="+",
        default=ALL_REGIONS,
        help="Regions to generate forcing for (default: all 5 regions)",
    )
    parser.add_argument(
        "--output-base-dir",
        type=Path,
        default=DEFAULT_OUTPUT_BASE,
        help="Base output directory for WW3 regional forcing files",
    )
    args = parser.parse_args()

    try:
        wrf_files = sorted(list(args.wrf_dir.glob("wrfout_d02_*")))
        if not wrf_files:
            raise FileNotFoundError(f"No wrfout_d02_* files found in {args.wrf_dir}")

        print(f"Found {len(wrf_files)} wrfout_d02_* files in {args.wrf_dir}")

        results = {}
        for region_id in args.regions:
            output_dir = args.output_base_dir / region_id
            print(f"Generating WW3 wind forcing for region '{region_id}' at {output_dir}...")
            manifest = extract_and_interpolate_wrf_wind(
                wrf_files=wrf_files,
                region_id=region_id,
                output_dir=output_dir,
            )
            results[region_id] = manifest
            print(f"  ✅ Complete: {manifest['timestamps']} timestamps from {manifest['start_time']} to {manifest['end_time']}")

        print("\nSummary:")
        print(json.dumps(results, indent=2))
        return 0
    except Exception as exc:
        print(f"❌ Error in prepare_ww3_wind_from_wrf.py: {exc}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
