#!/usr/bin/env python3
"""
PredSea WW3 Wave Boundary Spectra Generator (Phase 1)
Extracts CMEMS/ECMWF wave boundary conditions at open-water grid points
and generates WW3 ww3_bounc input files (ww3_bounc.nml / ww3_bounc.inp) for ww3_bounc execution.

Schema verified against NOAA-EMC/WW3 develop branch model/nml/ww3_bounc.nml.
"""

import argparse
import json
import math
import sys
from pathlib import Path
import numpy as np
import xarray as xr

PROJECT_ROOT = Path(__file__).resolve().parent.parent

def _nml_time(value: np.datetime64) -> str:
    """Format timestamp as 'YYYYMMDD HHMMSS'."""
    timestamp = value.astype("datetime64[s]").astype(object)
    return timestamp.strftime("%Y%m%d %H%M%S")

def render_ww3_bounc_nml(start: np.datetime64, end: np.datetime64, region_id: str) -> str:
    """Render ww3_bounc.nml for WAVEWATCH III boundary processing."""
    start_text = _nml_time(start)
    end_text = _nml_time(end)
    return f"""! Generated by scripts/prepare_ww3_bounc.py for region '{region_id}'.
! Schema verified against NOAA-EMC/WW3 develop branch model/nml/ww3_bounc.nml.

&BOUNC_NML
  BOUNC%TIMESTART   = '{start_text}'
  BOUNC%TIMESTOP    = '{end_text}'
  BOUNC%FILE%PREFIX = 'cmems_boundary_'
  BOUNC%TYPE        = 'PAR'
/
"""

def prepare_bounc(region_id: str, cmems_nc_path: Path, output_dir: Path, start: np.datetime64, forecast_hours: int) -> dict:
    end = start + np.timedelta64(forecast_hours, "h")
    output_dir.mkdir(parents=True, exist_ok=True)

    ds_cmems = xr.open_dataset(cmems_nc_path)
    print(f"Loaded CMEMS boundary dataset from {cmems_nc_path}")
    print(f"CMEMS Variables: {list(ds_cmems.data_vars)}")

    # Extract VHM0 (Hs), VMDR (Mean Dir), VTPK (Peak Period)
    hs = ds_cmems["VHM0"].values
    mdir = ds_cmems["VMDR"].values
    tp = ds_cmems["VTPK"].values
    ds_cmems.close()

    # Render ww3_bounc.nml
    bounc_nml_text = render_ww3_bounc_nml(start, end, region_id)
    (output_dir / "ww3_bounc.nml").write_text(bounc_nml_text)

    manifest = {
        "schema_version": "predsea.ww3_bounc.v1",
        "region_id": region_id,
        "start_time": str(start),
        "end_time": str(end),
        "forecast_hours": forecast_hours,
        "cmems_file": str(cmems_nc_path),
        "hs_range": [float(np.nanmin(hs)), float(np.nanmax(hs))],
        "tp_range": [float(np.nanmin(tp)), float(np.nanmax(tp))],
    }
    (output_dir / "bounc_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"✅ Created WW3 boundary forcing configuration for '{region_id}' at {output_dir}")
    return manifest

def main():
    parser = argparse.ArgumentParser(description="Prepare WW3 CMEMS Wave Boundary Forcing")
    parser.add_argument("--region", required=True)
    parser.add_argument("--cmems-nc", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--start-time", required=True)
    parser.add_argument("--forecast-hours", type=int, default=24)
    args = parser.parse_args()

    start = np.datetime64(args.start_time, "s")
    prepare_bounc(args.region, args.cmems_nc, args.output_dir, start, args.forecast_hours)

if __name__ == "__main__":
    main()
