#!/usr/bin/env python3
"""
PredSea WW3 forcing preparation utility -- Phase 0 6h smoke test
(docs/ww3-migration-plan-2026-08-04.md).

Prepares the inputs `ww3_prnc`, `ww3_shel`, and `ww3_ounf` need for a quick, wind-only
forecast: a CF-compliant wind NetCDF (ww3_prnc's input), the ww3_prnc.nml
that describes it, the ww3_shel.nml that runs the model, and the
ww3_ounf.nml that converts native gridded output to NetCDF.

Deliberately scoped down from a full production run for this first WW3
smoke test:
  - Wind forcing only. No ocean current forcing (INPUT_NML%CURRENTS
    defaults to 'F' when omitted) and no wave boundary spectra at the 66
    open-water boundary points identified in ww3_grid.nml (see
    scripts/prepare_ww3_grid.py). This mirrors how the original SWAN
    convergence investigation isolated variables one at a time -- the
    question for this run is simply "does ww3_shel step forward in time
    without hanging/crashing," not "is the physics accurate yet." Wave
    boundary spectra (via ww3_bounc) are a Phase 1 addition once this
    smoke test passes.
  - Reuses the exact same ECMWF wind source/interpolation logic as SWAN's
    own prepare_swan_run.py (_open_wind/_linear_time_interpolate), so both
    models are being driven by the identical wind field for later
    comparison.

Schema verified directly against the live NOAA-EMC/WW3 develop branch
source (model/nml/ww3_prnc.nml, model/nml/ww3_shel.nml, and
model/nml/ww3_ounf.nml, fetched
2026-08-04) -- namelist names/defaults below are transcribed from those
files, not guessed.

Usage:
    python3 scripts/prepare_ww3_forcing.py --region alboran_1km \\
        --wind-grib /path/to/ecmwf_wind.grib2 \\
        --output-dir simulation/marine/ww3/grids/alboran_1km \\
        --start-time 2026-08-04T00:00:00 --forecast-hours 6
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import xarray as xr

try:
    from scripts.prepare_swan_run import _open_wind
except ModuleNotFoundError:  # Direct execution from the scripts directory.
    from prepare_swan_run import _open_wind

PROJECT_ROOT = Path(__file__).resolve().parent.parent
REGIONS_DIR = PROJECT_ROOT / "simulation" / "marine" / "regions"


def load_region(region_id: str) -> dict:
    profile_path = REGIONS_DIR / f"{region_id}.json"
    if not profile_path.exists():
        raise FileNotFoundError(f"No region profile found at {profile_path}")
    return json.loads(profile_path.read_text())


def _nml_time(value: np.datetime64) -> str:
    """WW3 namelist time format, per ww3_shel.nml/ww3_prnc.nml's own
    examples: 'YYYYMMDD HHMMSS'."""
    timestamp = value.astype("datetime64[s]").astype(object)
    return timestamp.strftime("%Y%m%d %H%M%S")


def write_wind_netcdf(u: xr.DataArray, v: xr.DataArray, output_path: Path) -> None:
    """Write a CF-compliant wind NetCDF matching ww3_prnc's FILE_NML contract
    (model/nml/ww3_prnc.nml): dims time/latitude/longitude, a real time
    units+calendar attribute, and field variables named to match
    FILE%VAR(1)/FILE%VAR(2) ('U'/'V' below).
    """
    dataset = xr.Dataset(
        {
            "U": (("time", "latitude", "longitude"), np.asarray(u.values)),
            "V": (("time", "latitude", "longitude"), np.asarray(v.values)),
        },
        coords={
            "time": u.time.values,
            "latitude": u.latitude.values,
            "longitude": u.longitude.values,
        },
    )
    dataset["time"].encoding["units"] = "seconds since 1970-01-01T00:00:00Z"
    dataset["time"].encoding["calendar"] = "standard"
    dataset.to_netcdf(output_path, format="NETCDF4_CLASSIC")


def render_ww3_prnc_nml(start: np.datetime64, end: np.datetime64, wind_filename: str) -> str:
    return f"""\
! Generated by scripts/prepare_ww3_forcing.py.
! Schema verified against NOAA-EMC/WW3 develop branch model/nml/ww3_prnc.nml
! (fetched 2026-08-04).

&FORCING_NML
  FORCING%TIMESTART         = '{_nml_time(start)}'
  FORCING%TIMESTOP          = '{_nml_time(end)}'
  FORCING%FIELD%WINDS       = t
  FORCING%GRID%LATLON       = t
/

&FILE_NML
  FILE%FILENAME      = '{wind_filename}'
  FILE%LONGITUDE     = 'longitude'
  FILE%LATITUDE      = 'latitude'
  FILE%VAR(1)        = 'U'
  FILE%VAR(2)        = 'V'
/
"""


def render_ww3_shel_nml(region_id: str, start: np.datetime64, end: np.datetime64, enable_boundaries: bool = False) -> str:
    start_text = _nml_time(start)
    end_text = _nml_time(end)
    bound_flag = "'T'" if enable_boundaries else "'F'"
    return f"""\
! Generated by scripts/prepare_ww3_forcing.py for region '{region_id}'.
! Schema verified against NOAA-EMC/WW3 develop branch model/nml/ww3_shel.nml.

&DOMAIN_NML
  DOMAIN%START  = '{start_text}'
  DOMAIN%STOP   = '{end_text}'
/

&INPUT_NML
  INPUT%FORCING%WINDS      = 'T'
  INPUT%FORCING%BOUNDARIES = {bound_flag}
/

&OUTPUT_TYPE_NML
  TYPE%FIELD%LIST     = 'HS DIR SPR WND DTD FC CFX'
/

&OUTPUT_DATE_NML
  DATE%FIELD%START         = '{start_text}'
  DATE%FIELD%STRIDE        = '3600'
  DATE%FIELD%STOP          = '{end_text}'
/

&OUTPUT_PATH_NML
  PATH%GRD_OUT = './'
  PATH%PNT_OUT = './'
  PATH%RST_OUT = './'
/
"""


def render_ww3_ounf_nml(start: np.datetime64, end: np.datetime64) -> str:
    """Configure ww3_ounf to read ww3_shel's native ``out_grd.ww3`` output."""
    time_count = int((end - start) / np.timedelta64(1, "h")) + 1
    return f"""\
! Generated by scripts/prepare_ww3_forcing.py.
! Schema verified against NOAA-EMC/WW3 develop branch model/nml/ww3_ounf.nml.
! ww3_ounf reads the fixed native input name 'out_grd.ww3', produced in
! PATH%GRD_OUT by ww3_shel; PATH%GRD_OUT = './' therefore places it here.

&FIELD_NML
  FIELD%TIMESTART  = '{_nml_time(start)}'
  FIELD%TIMESTRIDE = '3600'
  FIELD%TIMECOUNT  = '{time_count}'
  FIELD%LIST       = 'HS DIR SPR WND DTD FC CFX'
  FIELD%SAMEFILE   = T
  FIELD%TYPE       = 4
/

&FILE_NML
  FILE%PREFIX = 'ww3.'
  FILE%NETCDF = 4
/
"""


def prepare(
    region_id: str,
    wind_grib_path: Path,
    output_dir: Path,
    start: np.datetime64,
    forecast_hours: int,
) -> dict:
    if forecast_hours <= 0:
        raise ValueError("forecast_hours must be positive")
    region = load_region(region_id)
    bbox = region["bbox"]
    end = start + np.timedelta64(forecast_hours, "h")
    output_dir.mkdir(parents=True, exist_ok=True)

    u, v = _open_wind(wind_grib_path, start, end, bbox)

    wind_filename = "wind.nc"
    write_wind_netcdf(u, v, output_dir / wind_filename)

    (output_dir / "ww3_prnc.nml").write_text(
        render_ww3_prnc_nml(start, end, wind_filename)
    )
    (output_dir / "ww3_shel.nml").write_text(
        render_ww3_shel_nml(region_id, start, end)
    )
    (output_dir / "ww3_ounf.nml").write_text(
        render_ww3_ounf_nml(start, end)
    )

    manifest = {
        "schema_version": "predsea.ww3_forcing_input.v1",
        "region_id": region_id,
        "start_time": str(start),
        "end_time": str(end),
        "forecast_hours": forecast_hours,
        "wind": {
            "source": "ECMWF",
            "timestamps": int(u.sizes["time"]),
        },
        "scope": "wind-only smoke test -- no currents, no wave boundary spectra",
    }
    (output_dir / "forcing_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--region", required=True)
    parser.add_argument("--wind-grib", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--start-time", required=True)
    parser.add_argument("--forecast-hours", type=int, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    start = np.datetime64(args.start_time, "s")
    manifest = prepare(
        args.region,
        args.wind_grib,
        args.output_dir,
        start,
        args.forecast_hours,
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
