steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=Dockerfile
      - --tag=${_IMAGE}
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - run
      - --rm
      - --entrypoint=/bin/sh
      - ${_IMAGE}
      - -c
      - test -x /usr/local/bin/swan.exe && ldd /usr/local/bin/swan.exe
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: europe-west1-docker.pkg.dev/predsea-api/predsea-simulations/swan:41.51
options:
  logging: CLOUD_LOGGING_ONLY
